GCMarker = c( "CD38", "CD83","CXCR4","CXCR5","AICDA","IRF8","CD40","IGHG1")
TFH = c("BCL6", "CXCR5", "ICOS", "IL21", "SH2D1A", "IRF4","PDCD1")
humoralgenes<- read_csv("/home/divya/Misc/sindhi/GO_term_summary_20241031_140920.csv")
humoralgenes=data.frame(humoralgenes)
humoralgenes = unique(unlist(humoralgenes[,"...12"]))
TF_TFs = sets::as.set(c("CD4", "IL21", "PDCD1", "CXCR3", "CCR6", "ICOS", "IRF4", "BCL6", "CXCR5", "CXCL13", "IL4","ASCL2", "TCF", "MAF", "BATF"))
GC_TFs = sets::as.set(c("BCL6", "FOXO1", "FOXP1" ))
GCZones= sets::as.set(c("CD83" , "CXCR4"))
cd40Signaling = sets::as.set(c("CD40", "TRAF1", "ICAM1"))
nfkbactivation = sets::as.set(c("NFKB2", "RELB", "NFKB1", "REL"))
ProliferationdarkZoneBcells = sets::as.set(c("PCNA", "MKI67", "CDK1", "CDC20", "MYC"))
memoryBcells = sets::as.set(c("PRDM1", "CCR6", "CD27", "XBP1", "IRF4", "MZB1", "TNFRSF17"))
otherMarkers = sets::as.set(c("AICDA" , "BCL2A1", "EZH2", "E2F1"))
calciumsignaling = sets::as.set(c("PTPN6", "CD22"))
BCRgenes = sets::as.set(c("BTK", "BLK", "BLNK"))
